innabox/fulfillment-service

- manifests/ca/ca-certificate.yaml
- manifests/ca/ca-issuer.yaml
- manifests/ca/issuer.yaml
- manifests/ca/kustomization.yaml
- manifests/database/client-cert.yaml
- manifests/database/files/access.conf
- manifests/database/files/server.conf
- manifests/database/kustomization.yaml
- manifests/database/server-cert.yaml
- manifests/database/statefulset.yaml
- manifests/service/deployment.yaml
This patch changes the configuration of the PostgreSQL database so that TLS is enabled, and configured to require client certificates. The certificates for the database server and client are genered using [cert-manager](https://cert-manager.io).
> Use TLS for PostgreSQL communication

- internal/controllers/clusterorder/cluster_order_function.go
- internal/database/migrations/1_cluster_templates.up.sql
This patch changes the part of the server that creates the K8S cluster orders so that it also puts the template parameters in the `spec.templateParameters` field. For example, for a cluster order like this:
```json
{
"object": {
"id": "e465dfad-e8af-4703-a37c-b115d1beb1a9",
"spec": {
"template_id": "ocp_4_17_small",
"template_parameters": {
"my_bool": {
"@type": "type.googleapis.com/google.protobuf.BoolValue",
"value": true
},
"my_int": {
"@type": "type.googleapis.com/google.protobuf.Int32Value",
"value": 42
},
"my_string": {
"@type": "type.googleapis.com/google.protobuf.StringValue",
"value": "my_value"
}
}
}
}
}
```
It creates a Kubernetes `ClusterOrder` like this:
```yaml
piVersion: cloudkit.openshift.io/v1alpha1
kind: ClusterOrder
metadata:
namespace: cloudkit-operator-system
name: …
```
> Copy template parameters to K8S cluster order

- .github/workflows/publish-image.yaml
This patch adds a GitHub workflow that publishes the container image to the GitHub container image registry for each push to the main branch and for each version tag.
In addition to the `latest` tag, for pushes to the main branch add a tag containing the short commit hash, for example:
ghcr.io/innabox/fulfillment-service:4719ed7
And for version tags like `v0.0.1` it will add the that version tag, for example:
ghcr.io/innabox/fulfillment-service:v0.0.1
> Add workflow to publish image

- manifests/service/files/envoy.yaml
Currently the CORS configuration of the Envoy proxy doesn't explicitly list `Authorization` as an allowed header. This seems to work fine with Firefox, but not with Chrome. This patch adds it.
> Add `Authorization` header to Envoy CORS filter

- internal/controllers/clusterorder/cluster_order_function.go
- internal/servers/clusters_server.go
When a order is created it is necessary to save the identifier of the selected hub, so that future operations on the order know which hub to use. This was already done, but accidentally lost in a previous change.
> Save selected hub

- internal/database/database_migrations_test.go
Names of migration files must end with `.up.sql`, but it is very easy to forget that and name them just `.sql`. This results in silently ignoring the migration. To avoid that this patch introduces a new test that verifies that all migration files end with `.up.sql`.
> Add test to verify names of SQL migration files

- buf.yaml
In order to push the private API to the buf schema registry it is necessary to give a name to the module.
> Add module name for the private API

- .github/actions/setup-go/action.yaml
- .github/workflows/check-pull-request.yaml
- Containerfile
- internal/cmd/start_server_cmd.go
- internal/logging/logger.go
- internal/logging/logging_writer.go
- internal/testing/command.go
- internal/testing/kind.go
- it/it_cluster_templates_test.go
- it/it_suite_test.go
- manifests/README.md
- manifests/base/service/certificate.yaml
- manifests/base/service/files/rules.yaml
This patch adds a collection of integration tests inside the `it` directory. These tests deploy the application to a _Kind_ cluster, and then check the behaviour using the API.
> Add integration tests

- internal/json/json_encoder.go
- internal/json/json_encoder_test.go
The protobuf `Any` type should be converted to the corresponding JSON type, but our custom encoder doesn't do that, instead it converts its fields. For example, an object created like this:
```go
object, err := anypb.New(wrapperspb.Bool(true))
```
Results in the following JSON:
```json
{
"type_url": "type.googleapis.com/google.protobuf.BoolValue"
"value": "CAE=",
}
```
But it should instead produce this:
```json
{
"@type": "type.googleapis.com/google.protobuf.BoolValue"
"value": true
}
```
This patch fixes that issue modifying our encoder so that it calls the protobuf one for well known types like `Any` and `Timestamp`.
> Fix JSON encoding of Any

- manifests/base/service/files/rules.yaml
The previous merge of `ClusterOrder` and `Cluster` concepts made the access rules for the `ClusterOrders` service obsolete. This patch removes them to maintain an up-to-date configuration, even though their existence was inconsequential.
> Remove cluster order concept from access rules

- manifests/base/service/files/rules.yaml
This changes the authorization rules to grant regular users permission to get the administrator password of clusters.
> Grant users permission to get cluster password

- .gitignore
- internal/testing/kind.go
- it/crds/clusterorders.cloudkit.openshift.io.yaml
- it/crds/hostedclusters.hypershift.openshift.io.yaml
- it/it_suite_test.go
This patch adds a new `AddCrdFile` method to the builder of the kind cluster that can be used to add CRD files that will be installed in the cluster. This is used to install the `ClusterOrder` and `HostedCluster` CRDs that will be used (in other patches) to write tests that verify that `ClusterOrder` objects are created correctly.
> Add support for installing CRDs in the integration tests cluster

- internal/servers/clusters_server.go
- internal/servers/clusters_server_test.go
This patch changes the clusters server so that it validates that the template parameters specified in the cluster are valid, and sets the default values for those that aren't specified.
> Validate and set default values of template parameters

- it/crds/clusterorders.cloudkit.openshift.io.yaml
- it/crds/hostedclusters.hypershift.openshift.io.yaml
- it/it_cluster_reconciler_test.go
- it/it_public_clusters_test.go
This patch adds a set of integration tests for the public clusters API, including the methods to get the kubeconfig of a cluster.
> Add public clusters API integration tests

- internal/servers/generic_server.go
Sending the Kubeconfig of hubs in notifications usually exceeds the size max size of the PostgreSQL `NOTIFY ...` mechanism, which is 8000 bytes. To avoid that this patch changes the generic server so that it removes the Kubeconfig from notifications.
A more general way to solve this would be to store the payloads in a separate table, and send only the identifier of the event in the payload of the `NOTIFY` mechanism. We will do that later.
Related: https://github.com/innabox/fulfillment-service/issues/82
Related: https://www.postgresql.org/docs/current/sql-notify.html
> Don't send hub Kubeconfig in notifications

- internal/database/database_listener.go
- internal/database/database_listener_test.go
- internal/database/database_notifier.go
- internal/database/database_notifier_test.go
- internal/database/migrations/7_add_notifications_table.up.sql
Currently the payload of notifications are sent using the PostgreSQL `NOTIFY` mechanism, but that mechanism has a limit of 8000 bytes, which is very easy to exceed. For example, it is exceeded for hub notifications that contain large Kubeconfigs. To address that issue this patch adds an unique identifier to each notification, and stores the payload in a new `notifications` table. The payload of the `NOTIFY` mechanism will now be only the identifer, and the listener will fetch the payload from the table.
Related: https://github.com/innabox/fulfillment-service/issues/82
Related: https://www.postgresql.org/docs/current/sql-notify.html
> Store notifications payload in a table

- internal/cmd/start_server_cmd.go
- internal/servers/cluster_templates_server.go
- internal/servers/cluster_templates_server_test.go
- internal/servers/clusters_server.go
- internal/servers/clusters_server_test.go
- internal/servers/generic_server.go
- internal/servers/host_classes_server.go
- internal/servers/host_classes_server_test.go
- internal/servers/private_cluster_templates_server.go
- internal/servers/private_clusters_server.go
- internal/servers/private_clusters_server_test.go
- internal/servers/private_host_classes_server.go
- internal/servers/private_hubs_server.go
Currently validation is implemented only in public servers. But it is desirable to have them also in the private servers. This patch does that by moving the validations to the private servers, and changing the public servers so that they delegate almost everything to the private servers. A side effect of that is that the generic private server no longer needs to map private objects to private objects, and the other way around, so it no longer needs to have two generic parameters.
> Move validation logic to private server and implement delegation

- .github/actions/setup-go/action.yaml
- Containerfile
- go.mod
Why are currently using Go 1.22, which is already unsupported. This patch updates to Go 1.24 because that is the newest one supported in RHEL UBI (which we need to update to 9.6 as well).
> Update to Go 1.24

- internal/servers/events_server.go
- internal/servers/private_events_server.go
Replace a call to `s.logger` with a call to the contextualized `logger` so
that the `Event rejected by filter` message includes context information.
> Use context logger in processEvent

- internal/cmd/start_controller_cmd.go
- internal/controllers/vm/vm_reconciler_function.go
- internal/kubernetes/gvks/kubernetes_gkvs.go
- internal/kubernetes/labels/kubernetes_labels.go
- internal/utils/template_parameters.go
- internal/utils/template_parameters_test.go
- Add VM reconciler function following cluster reconciler patterns
- Create VirtualMachine GVK and labels for Kubernetes resources
- Extract template parameter conversion to reusable utility function
- Update both VM and cluster reconcilers to use shared utility
- Add comprehensive tests for ConvertTemplateParametersToJSON function
- Integrate VM reconciler into controller startup process
The VM reconciler handles VirtualMachine lifecycle management by:
- Creating/updating/deleting VirtualMachine Kubernetes objects
- Selecting hubs for VM placement
- Processing template parameters for Kubernetes controllers
- Managing VM status and conditions
> Add VM reconciler

- .pre-commit-config.yaml
- charts/keycloak/Chart.yaml
- charts/keycloak/README.md
- charts/keycloak/files/realm.json
- charts/keycloak/templates/ca/ca-certificate.yaml
- charts/keycloak/templates/ca/ca-issuer.yaml
- charts/keycloak/templates/ca/issuer.yaml
- charts/keycloak/templates/database/client-cert.yaml
- charts/keycloak/templates/database/configmap.yaml
- charts/keycloak/templates/database/pvc.yaml
- charts/keycloak/templates/database/server-cert.yaml
- charts/keycloak/templates/database/service.yaml
- charts/keycloak/templates/database/statefulset.yaml
- charts/keycloak/templates/service/deployment.yaml
- charts/keycloak/templates/service/realm-configmap.yaml
- charts/keycloak/templates/service/server-cert.yaml
- charts/keycloak/templates/service/service.yaml
- charts/keycloak/values.yaml
- internal/testing/kind.go
- it/it_suite_test.go
- manifests/README.md
This commit introduces a comprehensive Keycloak Helm chart specifically designed for development and integration testing purposes within the fulfillment service project. The chart provides a complete Keycloak deployment that includes both the authentication service and its required PostgreSQL database, along with all necessary TLS certificates and configuration.
The Keycloak instance comes pre-configured with a test realm containing sample users, roles, and client configurations that will support authentication and authorization testing scenarios. The chart is designed to run efficiently in Kind clusters and includes all the infrastructure components needed for a functional identity provider setup, including certificate authorities, database persistence, and service networking. …
> Add Keycloak Helm chart for development and integration testing

- manifests/base/service/authconfig.yaml
Different flavours of Kubernetes use different token audiences (the value of the `aud` claim). Kind uses the full DNS name `kubernetes.default.svc.cluster.local`, but OpenShift uses the `kubernetes.default.svc` abbreviation.
> Add alternative name for Kubernetes token audience

- .vscode/launch.json
- internal/controllers/reconciler.go
- internal/network/grpc_client.go
- internal/network/grpc_client_flags.go
- manifests/base/controller/deployment.yaml
- manifests/base/service/deployment.yaml
- manifests/base/service/files/envoy.yaml
This change enables the gRPC keep alive functionality in an attempt to avoid connections being forcibly closed by proxies, particularly Envoy in our deployment environment. We have been experiencing intermittent connection issues that we haven't been able to fully identify, but they appear to be related to idle connection timeouts at the proxy layer.
The implementation adds a new `--grpc-keep-alive` command line flag allowing us to specify an interval for periodic keep alive events. When configured, the client will periodically ping the server to verify that the connection is alive. This should significantly reduce the chances of proxy-initiated connection drops during periods of low event activity.
In addition, in the Envoy configuration a new route is added specifically for the `Watch` …
> Add keep alive to gRPC client to prevent disconnections

- Containerfile
Currently the `git` command isn't available in the container image that is used to build the service. As a result the `go build` command isn't able to find the value for the `vcs.revision` build setting, and therefore the `version` command prints `unknown`:
```
$ podman run ... /usr/local/bin/fulfillment-service version | jq
{
"time": "2025-10-08T08:31:40Z",
"level": "INFO",
"msg": "Command",
"args": [
"/usr/local/bin/fulfillment-service",
"version"
]
}
{
"time": "2025-10-08T08:31:40Z",
"level": "INFO",
"msg": "Build",
"go": "go1.24.6 (Red Hat 1.24.6-1.el9_6)",
"os": "linux",
"arch": "amd64"
}
{
"time": "unknown",
"level": "INFO",
"msg": "Version",
"commit": "unknown"
}
```
To avoid that this patch adds the `git` command to the container image. The `version` command will now print this: …
> Add `git` to builder image
